spring:
  profiles:
    active: real

---
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: root
    driver-class-name: org.h2.Driver
    schema: classpath*:db/mysql/schema.sql
    initialization-mode: always

handlebars:
  prefix: classpath:templates/
  suffix: .html
---